spring:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  datasource:
    url: ${RDS_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${RDS_DB_USERNAME}
    password: ${RDS_DB_PASSWORD}
